flags: {}
extra-package-dbs: []
packages:
        - '.'
        - location: ../rasa
          subdirs:
            - rasa
            - text-lens
          extra-dep: true

extra-deps:  []

resolver: lts-7.11
pvp-bounds: both
